[project]
name = "hw-5-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.4",
    "numpy>=2.1.2",
    "requests>=2.32.3",
    "rich>=13.9.4",
    "scikit-learn==1.5.2",
]
